//! Durable, local playback resume state.
//!
//! This module records the last known playback position for one concrete
//! video in ANKAI's SQLCipher-encrypted [`crate::db::Db`]. A row is keyed
//! by `(provider, media_id, episode_id)`: `provider` names the catalog or
//! resolver namespace (for example `cinemeta`), `media_id` is that
//! provider's stable title id, and `episode_id` identifies a particular
//! episode. [`PlaybackKey::movie`] uses no episode id for a movie or other
//! single-video title; the database stores that `None` as an empty string
//! so SQLite's composite primary-key behavior stays deterministic.
//!
//! This is deliberately distinct from [`crate::anime`]'s watchlist. The
//! watchlist stores a coarse count of watched AniList episodes, while this
//! module is provider-agnostic and stores exact seconds for movies, series,
//! and catalogs that have no AniList relationship. Updating one does not
//! implicitly update the other.
//!
//! Calls are synchronous and local. There is no cloud sync, cross-device
//! conflict resolution, periodic autosave timer, or automatic completion
//! threshold here; the client owns those policies and calls [`save`],
//! [`save_with_metadata`], or [`mark_completed`] at the appropriate player
//! events. Metadata is stored in the same SQLCipher-encrypted database.
//! Treat `stream_url` as sensitive even so: configured addon URLs can embed
//! access tokens in their path or query, and callers must not log or export
//! the field casually.

use rusqlite::OptionalExtension;
use serde::{Deserialize, Serialize};

use crate::db::Db;
use crate::error::Error;

/// Stable identity for one playable video.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PlaybackKey {
    pub provider: String,
    pub media_id: String,
    /// `None` for a movie/single-video title; `Some` for one series episode.
    pub episode_id: Option<String>,
}

impl PlaybackKey {
    /// Creates a key for a movie or another title represented by one video.
    pub fn movie(provider: impl Into<String>, media_id: impl Into<String>) -> Self {
        Self {
            provider: provider.into(),
            media_id: media_id.into(),
            episode_id: None,
        }
    }

    /// Creates a key for one episode of a series.
    pub fn episode(
        provider: impl Into<String>,
        media_id: impl Into<String>,
        episode_id: impl Into<String>,
    ) -> Self {
        Self {
            provider: provider.into(),
            media_id: media_id.into(),
            episode_id: Some(episode_id.into()),
        }
    }
}

/// The last persisted playback state for one video.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlaybackProgress {
    pub key: PlaybackKey,
    pub position_seconds: f64,
    pub duration_seconds: f64,
    pub completed: bool,
    /// Optional display title cached for an offline/restart resume shelf.
    pub title: Option<String>,
    /// Optional HTTP(S) artwork URL cached for an offline/restart resume shelf.
    pub poster_url: Option<String>,
    /// Optional direct HTTP(S) playback URL used to resume without resolving again.
    ///
    /// This can contain configured-addon credentials or access tokens. It is
    /// encrypted at rest by [`Db`], but should still be treated as sensitive
    /// and kept out of diagnostics and analytics.
    pub stream_url: Option<String>,
    /// UTC timestamp generated by SQLite in RFC 3339-like text form.
    pub updated_at: String,
}

/// Optional context stored alongside an exact resume position.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlaybackMetadata {
    pub title: Option<String>,
    pub poster_url: Option<String>,
    /// A direct HTTP(S) media URL. Configured or tokenized URLs are sensitive
    /// even though this value is persisted only in ANKAI's encrypted database.
    pub stream_url: Option<String>,
}

const MAX_TITLE_CHARS: usize = 256;
const MAX_URL_BYTES: usize = 8_192;
const SELECT_COLUMNS: &str = "provider, media_id, episode_id, position_seconds, \
    duration_seconds, completed, title, poster_url, stream_url, updated_at";

/// Inserts or replaces the current progress for `key`.
///
/// Identifiers must be non-empty (and an episode id, when present, must
/// also be non-empty). Positions must be finite and non-negative;
/// durations must be finite and strictly positive; a position past its
/// duration is rejected. Validation happens before SQLite is touched, so a
/// rejected update cannot overwrite an earlier valid resume point.
pub fn save(
    db: &Db,
    key: &PlaybackKey,
    position_seconds: f64,
    duration_seconds: f64,
    completed: bool,
) -> Result<PlaybackProgress, Error> {
    validate_key(key)?;
    validate_times(position_seconds, duration_seconds)?;

    db.connection()
        .execute(
            "INSERT INTO playback_progress
                (provider, media_id, episode_id, position_seconds, duration_seconds, completed)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT(provider, media_id, episode_id) DO UPDATE SET
                position_seconds = excluded.position_seconds,
                duration_seconds = excluded.duration_seconds,
                completed        = excluded.completed,
                updated_at       = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')",
            rusqlite::params![
                key.provider,
                key.media_id,
                episode_id_for_db(key),
                position_seconds,
                duration_seconds,
                completed,
            ],
        )
        .map_err(|e| Error::Db(format!("failed to save playback progress for {key:?}: {e}")))?;

    load(db, key)?.ok_or_else(|| {
        Error::Db(format!(
            "playback progress for {key:?} missing immediately after save"
        ))
    })
}

/// Inserts or replaces progress and the optional UI/playback metadata.
///
/// The title is limited to 256 characters and may not be blank or contain
/// control characters. Poster and stream URLs must be absolute HTTP(S) URLs
/// with a host. `None` explicitly clears that field during an upsert. In
/// contrast, the metadata-unaware [`save`] function preserves metadata that
/// is already attached to a row, making it safe for frequent player autosaves.
pub fn save_with_metadata(
    db: &Db,
    key: &PlaybackKey,
    position_seconds: f64,
    duration_seconds: f64,
    completed: bool,
    metadata: &PlaybackMetadata,
) -> Result<PlaybackProgress, Error> {
    validate_key(key)?;
    validate_times(position_seconds, duration_seconds)?;
    validate_metadata(metadata)?;

    db.connection()
        .execute(
            "INSERT INTO playback_progress
                (provider, media_id, episode_id, position_seconds, duration_seconds, completed,
                 title, poster_url, stream_url)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
             ON CONFLICT(provider, media_id, episode_id) DO UPDATE SET
                position_seconds = excluded.position_seconds,
                duration_seconds = excluded.duration_seconds,
                completed        = excluded.completed,
                title            = excluded.title,
                poster_url       = excluded.poster_url,
                stream_url       = excluded.stream_url,
                updated_at       = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')",
            rusqlite::params![
                key.provider,
                key.media_id,
                episode_id_for_db(key),
                position_seconds,
                duration_seconds,
                completed,
                metadata.title,
                metadata.poster_url,
                metadata.stream_url,
            ],
        )
        .map_err(|e| {
            Error::Db(format!(
                "failed to save playback progress metadata for {key:?}: {e}"
            ))
        })?;

    load(db, key)?.ok_or_else(|| {
        Error::Db(format!(
            "playback progress for {key:?} missing immediately after metadata save"
        ))
    })
}

/// Loads the current progress for `key`, or `None` if it has never been saved.
pub fn load(db: &Db, key: &PlaybackKey) -> Result<Option<PlaybackProgress>, Error> {
    validate_key(key)?;

    db.connection()
        .query_row(
            &format!(
                "SELECT {SELECT_COLUMNS} FROM playback_progress
                 WHERE provider = ?1 AND media_id = ?2 AND episode_id = ?3"
            ),
            rusqlite::params![key.provider, key.media_id, episode_id_for_db(key)],
            row_to_progress,
        )
        .optional()
        .map_err(|e| Error::Db(format!("failed to load playback progress for {key:?}: {e}")))
}

/// Returns the most recently updated incomplete resume points.
///
/// Fresh, never-started rows (`position_seconds == 0`), completed rows, and
/// rows already at their duration are excluded. The last case makes this
/// query resilient to a client being terminated after its final position
/// save but before its explicit [`mark_completed`] event. The result is
/// newest-first and capped at `limit`; a zero limit returns an empty vector.
pub fn list_resumable_recent(db: &Db, limit: usize) -> Result<Vec<PlaybackProgress>, Error> {
    let limit = i64::try_from(limit).unwrap_or(i64::MAX);
    let mut stmt = db
        .connection()
        .prepare(&format!(
            "SELECT {SELECT_COLUMNS} FROM playback_progress
             WHERE completed = 0
               AND position_seconds > 0
               AND position_seconds < duration_seconds
             ORDER BY updated_at DESC, provider ASC, media_id ASC, episode_id ASC
             LIMIT ?1"
        ))
        .map_err(|e| Error::Db(format!("failed to prepare resumable progress query: {e}")))?;

    let rows = stmt
        .query_map(rusqlite::params![limit], row_to_progress)
        .map_err(|e| Error::Db(format!("failed to query resumable progress: {e}")))?;

    rows.collect::<Result<Vec<_>, _>>()
        .map_err(|e| Error::Db(format!("failed to read resumable progress row: {e}")))
}

/// Marks an existing progress row complete and moves its position to the end.
///
/// Returning an error for an unknown key prevents a completion event from
/// fabricating a row without a trustworthy media duration. Call [`save`]
/// at least once after media has loaded, then call this when playback ends.
pub fn mark_completed(db: &Db, key: &PlaybackKey) -> Result<PlaybackProgress, Error> {
    validate_key(key)?;

    let rows_changed = db
        .connection()
        .execute(
            "UPDATE playback_progress SET
                position_seconds = duration_seconds,
                completed = 1,
                updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
             WHERE provider = ?1 AND media_id = ?2 AND episode_id = ?3",
            rusqlite::params![key.provider, key.media_id, episode_id_for_db(key)],
        )
        .map_err(|e| {
            Error::Db(format!(
                "failed to mark playback progress complete for {key:?}: {e}"
            ))
        })?;

    if rows_changed == 0 {
        return Err(Error::Db(format!(
            "cannot mark unknown playback progress complete for {key:?}"
        )));
    }

    load(db, key)?.ok_or_else(|| {
        Error::Db(format!(
            "playback progress for {key:?} missing immediately after completion"
        ))
    })
}

/// Removes a saved resume point. Clearing an already-absent key is a no-op.
pub fn clear(db: &Db, key: &PlaybackKey) -> Result<(), Error> {
    validate_key(key)?;

    db.connection()
        .execute(
            "DELETE FROM playback_progress
             WHERE provider = ?1 AND media_id = ?2 AND episode_id = ?3",
            rusqlite::params![key.provider, key.media_id, episode_id_for_db(key)],
        )
        .map_err(|e| {
            Error::Db(format!(
                "failed to clear playback progress for {key:?}: {e}"
            ))
        })?;
    Ok(())
}

fn validate_key(key: &PlaybackKey) -> Result<(), Error> {
    validate_identifier("provider", &key.provider)?;
    validate_identifier("media_id", &key.media_id)?;
    if let Some(episode_id) = &key.episode_id {
        validate_identifier("episode_id", episode_id)?;
    }
    Ok(())
}

fn validate_identifier(field: &str, value: &str) -> Result<(), Error> {
    if value.trim().is_empty() {
        return Err(Error::Db(format!(
            "playback progress {field} cannot be empty"
        )));
    }
    if value.contains('\0') {
        return Err(Error::Db(format!(
            "playback progress {field} cannot contain a NUL byte"
        )));
    }
    Ok(())
}

fn validate_times(position_seconds: f64, duration_seconds: f64) -> Result<(), Error> {
    if !position_seconds.is_finite() || position_seconds < 0.0 {
        return Err(Error::Db(format!(
            "playback position must be finite and non-negative, got {position_seconds}"
        )));
    }
    if !duration_seconds.is_finite() || duration_seconds <= 0.0 {
        return Err(Error::Db(format!(
            "playback duration must be finite and positive, got {duration_seconds}"
        )));
    }
    if position_seconds > duration_seconds {
        return Err(Error::Db(format!(
            "playback position {position_seconds} cannot exceed duration {duration_seconds}"
        )));
    }
    Ok(())
}

fn validate_metadata(metadata: &PlaybackMetadata) -> Result<(), Error> {
    if let Some(title) = &metadata.title {
        if title.trim().is_empty() {
            return Err(Error::Db(
                "playback progress title cannot be blank".to_string(),
            ));
        }
        if title.chars().count() > MAX_TITLE_CHARS {
            return Err(Error::Db(format!(
                "playback progress title cannot exceed {MAX_TITLE_CHARS} characters"
            )));
        }
        if title.chars().any(char::is_control) {
            return Err(Error::Db(
                "playback progress title cannot contain control characters".to_string(),
            ));
        }
    }

    validate_http_url("poster_url", metadata.poster_url.as_deref())?;
    validate_http_url("stream_url", metadata.stream_url.as_deref())?;
    Ok(())
}

fn validate_http_url(field: &str, value: Option<&str>) -> Result<(), Error> {
    let Some(value) = value else {
        return Ok(());
    };

    if value.len() > MAX_URL_BYTES {
        return Err(Error::Db(format!(
            "playback progress {field} cannot exceed {MAX_URL_BYTES} bytes"
        )));
    }

    let parsed = reqwest::Url::parse(value)
        .map_err(|_| Error::Db(format!("playback progress {field} must be a valid URL")))?;
    if !matches!(parsed.scheme(), "http" | "https") || !parsed.has_host() {
        return Err(Error::Db(format!(
            "playback progress {field} must be an absolute HTTP(S) URL with a host"
        )));
    }
    Ok(())
}

fn episode_id_for_db(key: &PlaybackKey) -> &str {
    key.episode_id.as_deref().unwrap_or("")
}

fn row_to_progress(row: &rusqlite::Row<'_>) -> rusqlite::Result<PlaybackProgress> {
    let episode_id: String = row.get(2)?;
    Ok(PlaybackProgress {
        key: PlaybackKey {
            provider: row.get(0)?,
            media_id: row.get(1)?,
            episode_id: (!episode_id.is_empty()).then_some(episode_id),
        },
        position_seconds: row.get(3)?,
        duration_seconds: row.get(4)?,
        completed: row.get(5)?,
        title: row.get(6)?,
        poster_url: row.get(7)?,
        stream_url: row.get(8)?,
        updated_at: row.get(9)?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> Db {
        Db::open_in_memory("correct horse battery staple").unwrap()
    }

    #[test]
    fn save_load_and_upsert_round_trip_movie_and_episode_keys() {
        let db = setup();
        let movie = PlaybackKey::movie("cinemeta", "tt0133093");
        let episode = PlaybackKey::episode("cinemeta", "tt0388629", "1:4");

        let first = save(&db, &movie, 120.5, 8_160.0, false).unwrap();
        assert_eq!(first.key, movie);
        assert_eq!(first.position_seconds, 120.5);
        assert!(!first.completed);
        assert_eq!(first.title, None);
        assert_eq!(first.poster_url, None);
        assert_eq!(first.stream_url, None);
        assert!(!first.updated_at.is_empty());
        assert_eq!(load(&db, &movie).unwrap(), Some(first));

        let updated = save(&db, &movie, 900.0, 8_160.0, false).unwrap();
        assert_eq!(updated.position_seconds, 900.0);
        assert_eq!(load(&db, &movie).unwrap(), Some(updated));

        let episode_progress = save(&db, &episode, 42.0, 1_440.0, false).unwrap();
        assert_eq!(episode_progress.key.episode_id.as_deref(), Some("1:4"));
        assert_eq!(load(&db, &episode).unwrap(), Some(episode_progress));
        assert_ne!(load(&db, &movie).unwrap(), load(&db, &episode).unwrap());
    }

    #[test]
    fn metadata_upsert_round_trips_and_plain_save_preserves_it() {
        let db = setup();
        let key = PlaybackKey::episode("anime-addon", "anime:1", "1:3");
        let metadata = PlaybackMetadata {
            title: Some("Neon Genesis Evangelion — Episode 3".to_string()),
            poster_url: Some("https://images.example.test/eva.webp".to_string()),
            stream_url: Some(
                "https://stream.example.test/config-token/eva-03.mkv?access=secret".to_string(),
            ),
        };

        let saved = save_with_metadata(&db, &key, 240.0, 1_440.0, false, &metadata).unwrap();
        assert_eq!(saved.title, metadata.title);
        assert_eq!(saved.poster_url, metadata.poster_url);
        assert_eq!(saved.stream_url, metadata.stream_url);

        let autosaved = save(&db, &key, 300.0, 1_440.0, false).unwrap();
        assert_eq!(autosaved.position_seconds, 300.0);
        assert_eq!(autosaved.title, metadata.title);
        assert_eq!(autosaved.poster_url, metadata.poster_url);
        assert_eq!(autosaved.stream_url, metadata.stream_url);

        let replacement = PlaybackMetadata {
            title: Some("Episode 3".to_string()),
            poster_url: None,
            stream_url: Some("http://127.0.0.1:11470/media/eva-03".to_string()),
        };
        let updated = save_with_metadata(&db, &key, 360.0, 1_440.0, false, &replacement).unwrap();
        assert_eq!(updated.title, replacement.title);
        assert_eq!(updated.poster_url, None);
        assert_eq!(updated.stream_url, replacement.stream_url);
    }

    #[test]
    fn list_resumable_recent_excludes_zero_and_completed_and_honors_limit() {
        let db = setup();
        let older = PlaybackKey::episode("addon", "series-a", "1:1");
        let newer = PlaybackKey::episode("addon", "series-b", "1:2");
        let fresh = PlaybackKey::movie("addon", "not-started");
        let done = PlaybackKey::movie("addon", "finished");
        let ended_without_completion_event = PlaybackKey::movie("addon", "ended");

        save(&db, &older, 10.0, 100.0, false).unwrap();
        save(&db, &newer, 20.0, 100.0, false).unwrap();
        save(&db, &fresh, 0.0, 100.0, false).unwrap();
        save(&db, &done, 100.0, 100.0, true).unwrap();
        save(&db, &ended_without_completion_event, 100.0, 100.0, false).unwrap();

        // Make the ordering deterministic without sleeping or depending
        // on the host clock's timestamp resolution.
        db.connection()
            .execute(
                "UPDATE playback_progress SET updated_at = ?1
                 WHERE provider = ?2 AND media_id = ?3 AND episode_id = ?4",
                rusqlite::params!["2026-08-15T10:00:00.000Z", "addon", "series-a", "1:1"],
            )
            .unwrap();
        db.connection()
            .execute(
                "UPDATE playback_progress SET updated_at = ?1
                 WHERE provider = ?2 AND media_id = ?3 AND episode_id = ?4",
                rusqlite::params!["2026-08-15T11:00:00.000Z", "addon", "series-b", "1:2"],
            )
            .unwrap();

        let all = list_resumable_recent(&db, 10).unwrap();
        assert_eq!(
            all.iter().map(|item| &item.key).collect::<Vec<_>>(),
            vec![&newer, &older]
        );
        assert_eq!(list_resumable_recent(&db, 1).unwrap()[0].key, newer);
        assert!(list_resumable_recent(&db, 0).unwrap().is_empty());
    }

    #[test]
    fn mark_completed_moves_to_end_and_removes_from_resume_list() {
        let db = setup();
        let key = PlaybackKey::episode("cinemeta", "tt123", "2:8");
        save(&db, &key, 420.0, 1_500.0, false).unwrap();

        let completed = mark_completed(&db, &key).unwrap();
        assert!(completed.completed);
        assert_eq!(completed.position_seconds, completed.duration_seconds);
        assert!(list_resumable_recent(&db, 10).unwrap().is_empty());

        let unknown = PlaybackKey::movie("cinemeta", "unknown");
        assert!(mark_completed(&db, &unknown).is_err());
    }

    #[test]
    fn clear_is_idempotent() {
        let db = setup();
        let key = PlaybackKey::movie("cinemeta", "tt0111161");
        save(&db, &key, 60.0, 8_520.0, false).unwrap();

        clear(&db, &key).unwrap();
        assert_eq!(load(&db, &key).unwrap(), None);
        clear(&db, &key).unwrap();
    }

    #[test]
    fn invalid_input_is_rejected_without_overwriting_valid_progress() {
        let db = setup();
        let key = PlaybackKey::movie("cinemeta", "tt0133093");
        let valid = save(&db, &key, 30.0, 100.0, false).unwrap();

        for (position, duration) in [
            (-1.0, 100.0),
            (f64::NAN, 100.0),
            (10.0, 0.0),
            (10.0, f64::INFINITY),
            (101.0, 100.0),
        ] {
            assert!(save(&db, &key, position, duration, false).is_err());
        }
        assert_eq!(load(&db, &key).unwrap(), Some(valid));

        for invalid_key in [
            PlaybackKey::movie("", "media"),
            PlaybackKey::movie("provider", "  "),
            PlaybackKey::episode("provider", "media", ""),
            PlaybackKey::movie("bad\0provider", "media"),
        ] {
            assert!(save(&db, &invalid_key, 1.0, 2.0, false).is_err());
            assert!(load(&db, &invalid_key).is_err());
            assert!(clear(&db, &invalid_key).is_err());
        }
    }

    #[test]
    fn invalid_metadata_is_rejected_without_overwriting_valid_progress() {
        let db = setup();
        let key = PlaybackKey::movie("cinemeta", "tt0133093");
        let original_metadata = PlaybackMetadata {
            title: Some("The Matrix".to_string()),
            poster_url: Some("https://images.example.test/matrix.jpg".to_string()),
            stream_url: Some("https://stream.example.test/matrix.mkv".to_string()),
        };
        let valid = save_with_metadata(&db, &key, 30.0, 100.0, false, &original_metadata).unwrap();

        let invalid_metadata = [
            PlaybackMetadata {
                title: Some(" ".to_string()),
                ..original_metadata.clone()
            },
            PlaybackMetadata {
                title: Some(format!("{}x", "a".repeat(MAX_TITLE_CHARS))),
                ..original_metadata.clone()
            },
            PlaybackMetadata {
                title: Some("The\nMatrix".to_string()),
                ..original_metadata.clone()
            },
            PlaybackMetadata {
                poster_url: Some("file:///tmp/poster.jpg".to_string()),
                ..original_metadata.clone()
            },
            PlaybackMetadata {
                stream_url: Some("magnet:?xt=urn:btih:deadbeef".to_string()),
                ..original_metadata.clone()
            },
            PlaybackMetadata {
                stream_url: Some("/relative/video.mkv".to_string()),
                ..original_metadata.clone()
            },
        ];

        for metadata in invalid_metadata {
            assert!(save_with_metadata(&db, &key, 40.0, 100.0, false, &metadata).is_err());
        }
        assert_eq!(load(&db, &key).unwrap(), Some(valid));
    }
}
